In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv(r'diabetes.csv',decimal=",")
df

,patient_number,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,1,193,77,49,3.9,19,female,61,119,22.5,118,70,32,38,0.84,No diabetes
1,2,146,79,41,3.6,19,female,60,135,26.4,108,58,33,40,0.83,No diabetes
2,3,217,75,54,4.0,20,female,67,187,29.3,110,72,40,45,0.89,No diabetes
3,4,226,97,70,3.2,20,female,64,114,19.6,122,64,31,39,0.79,No diabetes
4,5,164,91,67,2.4,20,female,70,141,20.2,122,86,32,39,0.82,No diabetes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,386,227,105,44,5.2,83,female,59,125,25.2,150,90,35,40,0.88,No diabetes
386,387,226,279,52,4.3,84,female,60,192,37.5,144,88,41,48,0.85,Diabetes
387,388,301,90,118,2.6,89,female,61,115,21.7,218,90,31,41,0.76,No diabetes
388,389,232,184,114,2.0,91,female,61,127,24.0,170,82,35,38,0.92,Diabetes
389,390,165,94,69,2.4,92,female,62,217,39.7,160,82,51,51,1.00,No diabetes

In [6]:
df.dropna()
df

,patient_number,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,1,193,77,49,3.9,19,female,61,119,22.5,118,70,32,38,0.84,No diabetes
1,2,146,79,41,3.6,19,female,60,135,26.4,108,58,33,40,0.83,No diabetes
2,3,217,75,54,4.0,20,female,67,187,29.3,110,72,40,45,0.89,No diabetes
3,4,226,97,70,3.2,20,female,64,114,19.6,122,64,31,39,0.79,No diabetes
4,5,164,91,67,2.4,20,female,70,141,20.2,122,86,32,39,0.82,No diabetes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,386,227,105,44,5.2,83,female,59,125,25.2,150,90,35,40,0.88,No diabetes
386,387,226,279,52,4.3,84,female,60,192,37.5,144,88,41,48,0.85,Diabetes
387,388,301,90,118,2.6,89,female,61,115,21.7,218,90,31,41,0.76,No diabetes
388,389,232,184,114,2.0,91,female,61,127,24.0,170,82,35,38,0.92,Diabetes
389,390,165,94,69,2.4,92,female,62,217,39.7,160,82,51,51,1.00,No diabetes

In [15]:
df2 = df.drop(['height', 'chol_hdl_ratio', 'weight','height','hip', 'waist','patient_number'], axis=1)
df2

,cholesterol,glucose,hdl_chol,age,gender,bmi,systolic_bp,diastolic_bp,waist_hip_ratio,diabetes
0,193,77,49,19,female,22.5,118,70,0.84,No diabetes
1,146,79,41,19,female,26.4,108,58,0.83,No diabetes
2,217,75,54,20,female,29.3,110,72,0.89,No diabetes
3,226,97,70,20,female,19.6,122,64,0.79,No diabetes
4,164,91,67,20,female,20.2,122,86,0.82,No diabetes
...,...,...,...,...,...,...,...,...,...,...
385,227,105,44,83,female,25.2,150,90,0.88,No diabetes
386,226,279,52,84,female,37.5,144,88,0.85,Diabetes
387,301,90,118,89,female,21.7,218,90,0.76,No diabetes
388,232,184,114,91,female,24.0,170,82,0.92,Diabetes
389,165,94,69,92,female,39.7,160,82,1.00,No diabetes

In [9]:
df2['diabetes'].describe()

count             390
unique              2
top       No diabetes
freq              330
Name: diabetes, dtype: object

In [10]:
df2['cholesterol'].describe()

count    390.000000
mean     207.230769
std       44.666005
min       78.000000
25%      179.000000
50%      203.000000
75%      229.000000
max      443.000000
Name: cholesterol, dtype: float64

In [16]:
df2.to_csv('diabetes2.csv', index=False)